# Generated by Django 5.1.6 on 2025-03-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilem',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/papierosek.png', null=True, upload_to='profiles/'),
        ),
    ]
