# Generated by Django 5.1.6 on 2025-04-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profilem_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilem',
            name='verification_code',
            field=models.CharField(default=123456, max_length=6),
            preserve_default=False,
        ),
    ]
