# Generated by Django 5.1.6 on 2025-04-14 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profilem_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilem',
            name='verification_code_from_user',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
