# Generated by Django 5.1.6 on 2025-04-14 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profilem_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilem',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 14, 17, 21, 6, 274806)),
        ),
    ]
