# Generated by Django 5.1.6 on 2025-02-18 15:07

import embed_video.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsM',
            fields=[
                ('title', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('video', embed_video.fields.EmbedVideoField()),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('time', models.CharField(blank=True, max_length=15, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
