# Generated by Django 5.1.6 on 2025-03-16 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0002_alter_profilem_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectm',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='users.profilem'),
        ),
    ]
