# Generated by Django 5.1.6 on 2025-02-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_ranksm_reviewm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranksm',
            name='rank_image',
            field=models.ImageField(blank=True, default='files/images/unranked.png', null=True, upload_to=''),
        ),
    ]
