# Generated by Django 5.1.6 on 2025-03-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectm_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectm',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectm',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
