# Generated by Django 5.1.6 on 2025-03-17 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectm_age_alter_projectm_time'),
        ('users', '0002_alter_profilem_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranksm',
            name='project',
        ),
        migrations.AddField(
            model_name='ranksm',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='users.profilem'),
        ),
    ]
