# Generated by Django 5.1.6 on 2025-02-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_ranksm_rank_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranksm',
            name='rank_image',
            field=models.ImageField(blank=True, default='/unranked.png', null=True, upload_to=''),
        ),
    ]
