# Generated by Django 5.1.6 on 2025-04-10 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_reviewm_owner_alter_reviewm_value'),
        ('users', '0003_profilem_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewm',
            name='owner_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_owner', to='users.profilem'),
        ),
    ]
