# Generated by Django 5.1.6 on 2025-04-10 19:25

from django.db import migrations



def add_owner(apps, schema_editor):
    ReviewM = apps.get_model('projects', 'ReviewM')
    ProfileM = apps.get_model('users', 'ProfileM')
    for i in ReviewM.objects.all():
        profile = ProfileM.objects.get(id=i.owner)
        i.owner_new = profile
        i.save()




class Migration(migrations.Migration):




    dependencies = [
        ('projects', '0006_reviewm_owner_new'),
    ]

    operations = [ migrations.RunPython(add_owner)
    ]
