# Generated by Django 5.1.6 on 2025-04-10 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_custom_add_owner'),
        ('users', '0003_profilem_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewm',
            name='owner_new',
        ),
        migrations.AlterField(
            model_name='reviewm',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_owner', to='users.profilem'),
        ),
    ]
